#Configure here general information about the environment, such as SonarQube server connection details for example
#No information about specific project should appear here
sonar.projectKey=??
sonar.host.url=??
sonar.token=??
sonar.sources=??
sonar.exclusions=
sonar.test=??
sonar.language=javascript
# https://community.sonarsource.com/t/missing-blame-information-for-the-following-files/54505/2
sonar.scm.disabled=true
sonar.test.inclusions=tests/*.test.js
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.testExecutionReportPaths=./coverage/test-reporter.xml
sonar.sourceEnconding=UTF-8
