#project
sonar.projectKey=trafficlight-app-codecov
# keep port 9000 even if you map the port with ssh on port 9001
sonar.host.url=http://localhost:9000
# set the generated token
sonar.token=sqp_95e0c7f93d93f410244ea7a4578f0ec2dab7067d
sonar.sources=src
sonar.exclusions=
sonar.test=tests
sonar.language=javascript
# https://community.sonarsource.com/t/missing-blame-information-for-the-following-files/54505/2
sonar.scm.disabled=true
sonar.test.inclusions=tests/*.test.js
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.testExecutionReportPaths=./coverage/test-reporter.xml
sonar.sourceEnconding=UTF-8
